<?php

namespace Database\Seeders;

use App\Models\Alumni;
use Illuminate\Database\Seeder;

class AlumniSeeder extends Seeder
{
    public function run()
    {
        $alumnis = [
            [
                'name' => 'Alice Smith',
                'email' => 'alice@example.com',
                'major' => 'Computer Science',
                'graduation_year' => 2020,
                'employment_status' => 'Employed',
                'phone_number' => '081234567890',
                'address' => 'Surabaya',
            ],
            [
                'name' => 'Bob Johnson',
                'email' => 'bob@example.com',
                'major' => 'Informatics',
                'graduation_year' => 2020,
                'employment_status' => 'Unemployed',
                'phone_number' => '081234567891',
                'address' => 'Malang',
            ],
            [
                'name' => 'Charlie Brown',
                'email' => 'charlie@example.com',
                'major' => 'Informatics',
                'graduation_year' => 2020,
                'employment_status' => 'Freelancer',
                'phone_number' => '081234567892',
                'address' => 'Sidoarjo',
            ],
            [
                'name' => 'Diana Prince',
                'email' => 'diana@example.com',
                'major' => 'Computer Science',
                'graduation_year' => 2022,
                'employment_status' => 'Entrepreneur',
                'phone_number' => '081234567893',
                'address' => 'Gresik',
            ],
            [
                'name' => 'Evan Wright',
                'email' => 'evan@example.com',
                'major' => 'Information Systems',
                'graduation_year' => 2021,
                'employment_status' => 'Studying',
                'phone_number' => '081234567894',
                'address' => 'Lamongan',
            ],
            [
                'name' => 'Fiona Davis',
                'email' => 'fiona@example.com',
                'major' => 'Informatics',
                'graduation_year' => 2022,
                'employment_status' => 'Employed',
                'phone_number' => '081234567895',
                'address' => 'Surabaya',
            ],
            [
                'name' => 'George King',
                'email' => 'george@example.com',
                'major' => 'Informatics',
                'graduation_year' => 2020,
                'employment_status' => 'Freelancer',
                'phone_number' => '081234567896',
                'address' => 'Jombang',
            ],
            [
                'name' => 'Hannah Miles',
                'email' => 'hannah@example.com',
                'major' => 'Computer Science',
                'graduation_year' => 2022,
                'employment_status' => 'Entrepreneur',
                'phone_number' => '081234567897',
                'address' => 'Blitar',
            ],
            [
                'name' => 'Ian Clark',
                'email' => 'ian@example.com',
                'major' => 'Informatics',
                'graduation_year' => 2023,
                'employment_status' => 'Unemployed',
                'phone_number' => '081234567898',
                'address' => 'Kediri',
            ],
            [
                'name' => 'Jane Foster',
                'email' => 'jane@example.com',
                'major' => 'Information Systems',
                'graduation_year' => 2020,
                'employment_status' => 'Employed',
                'phone_number' => '081234567899',
                'address' => 'Mojokerto',
            ],
            // Tambahan 15 alumni
            [
                'name' => 'Kevin Hart',
                'email' => 'kevin@example.com',
                'major' => 'Software Engineering',
                'graduation_year' => 2021,
                'employment_status' => 'Freelancer',
                'phone_number' => '081234567900',
                'address' => 'Tulungagung',
            ],
            [
                'name' => 'Linda Scott',
                'email' => 'linda@example.com',
                'major' => 'Informatics',
                'graduation_year' => 2023,
                'employment_status' => 'Employed',
                'phone_number' => '081234567901',
                'address' => 'Pasuruan',
            ],
            [
                'name' => 'Michael Bay',
                'email' => 'michael@example.com',
                'major' => 'Information Systems',
                'graduation_year' => 2021,
                'employment_status' => 'Studying',
                'phone_number' => '081234567902',
                'address' => 'Probolinggo',
            ],
            [
                'name' => 'Nina Lee',
                'email' => 'nina@example.com',
                'major' => 'Computer Science',
                'graduation_year' => 2022,
                'employment_status' => 'Unemployed',
                'phone_number' => '081234567903',
                'address' => 'Madiun',
            ],
            [
                'name' => 'Oscar Wilde',
                'email' => 'oscar@example.com',
                'major' => 'Informatics',
                'graduation_year' => 2020,
                'employment_status' => 'Entrepreneur',
                'phone_number' => '081234567904',
                'address' => 'Bojonegoro',
            ],
            [
                'name' => 'Paula Dean',
                'email' => 'paula@example.com',
                'major' => 'Information Systems',
                'graduation_year' => 2023,
                'employment_status' => 'Employed',
                'phone_number' => '081234567905',
                'address' => 'Ngawi',
            ],
            [
                'name' => 'Quincy Adams',
                'email' => 'quincy@example.com',
                'major' => 'Computer Science',
                'graduation_year' => 2021,
                'employment_status' => 'Freelancer',
                'phone_number' => '081234567906',
                'address' => 'Pacitan',
            ],
            [
                'name' => 'Rachel Green',
                'email' => 'rachel@example.com',
                'major' => 'Informatics',
                'graduation_year' => 2023,
                'employment_status' => 'Studying',
                'phone_number' => '081234567907',
                'address' => 'Trenggalek',
            ],
            [
                'name' => 'Steve Rogers',
                'email' => 'steve@example.com',
                'major' => 'Software Engineering',
                'graduation_year' => 2022,
                'employment_status' => 'Employed',
                'phone_number' => '081234567908',
                'address' => 'Ponorogo',
            ],
            [
                'name' => 'Tina Brown',
                'email' => 'tina@example.com',
                'major' => 'Information Systems',
                'graduation_year' => 2020,
                'employment_status' => 'Entrepreneur',
                'phone_number' => '081234567909',
                'address' => 'Magetan',
            ],
            [
                'name' => 'Umar Syah',
                'email' => 'umar@example.com',
                'major' => 'Informatics',
                'graduation_year' => 2022,
                'employment_status' => 'Unemployed',
                'phone_number' => '081234567910',
                'address' => 'Batu',
            ],
            [
                'name' => 'Vera Wang',
                'email' => 'vera@example.com',
                'major' => 'Computer Science',
                'graduation_year' => 2021,
                'employment_status' => 'Freelancer',
                'phone_number' => '081234567911',
                'address' => 'Nganjuk',
            ],
            [
                'name' => 'William Tan',
                'email' => 'william@example.com',
                'major' => 'Software Engineering',
                'graduation_year' => 2020,
                'employment_status' => 'Studying',
                'phone_number' => '081234567912',
                'address' => 'Bondowoso',
            ],
            [
                'name' => 'Xena Grace',
                'email' => 'xena@example.com',
                'major' => 'Informatics',
                'graduation_year' => 2023,
                'employment_status' => 'Employed',
                'phone_number' => '081234567913',
                'address' => 'Situbondo',
            ],
            [
                'name' => 'Yusuf Ardi',
                'email' => 'yusuf@example.com',
                'major' => 'Information Systems',
                'graduation_year' => 2021,
                'employment_status' => 'Entrepreneur',
                'phone_number' => '081234567914',
                'address' => 'Tuban',
            ],
            [
                'name' => 'Zara Khan',
                'email' => 'zara@example.com',
                'major' => 'Software Engineering',
                'graduation_year' => 2022,
                'employment_status' => 'Employed',
                'phone_number' => '081234567915',
                'address' => 'Banyuwangi',
            ],
        ];

        foreach ($alumnis as $data) {
            Alumni::create($data);
        }
    }
}
